### ISSUE TITLE
What about GitHub Pages?

### ISSUE THREAD

**Issue by Peter-developer01** [kriks999/layouts#1]
### What do you thinking about to enable GitHub Pages?
I want to see your site (portfolio? layout?) online, @kriks999.
**As well, I'm everyday ready to help you.**
If you have any problems or questions, I'm ready to _help_ you.

_**Sincerely, @Peter-developer01.**_

**Comment by qwerty123-noname** [comment]
Oy, you are opening for me new featches on github, I didn't know about it, **thank you**!
When I complete  my first layout _(it will be soon)_ , I will study this new feature and of course if I have big problems, I will write you, @Peter-developer01 =)

_Today I haven't enough time for continue to do this work, but I wanna add some design+analytics in my front page._

**Comment by Peter-developer01** [comment]
Super! (I have no words more)

**Comment by Peter-developer01** [comment]
Hello, where is you?
Of course I can help you!
Or you don't want to enable GitHub Pages?
It will not take long!
Sincerely, @Peter-developer01.

**Comment by qwerty123-noname** [comment]
Sorry for the  late answer, @Peter-developer01. Today I was learning and after university did some upgrades for my first layout and front page(So I spent my day :innocent:).

I will be free in sunday, then I try to add GitHub Pages in my repo with layouts and for the future projects. If anything be incomprehensible I will write you in telegram.

**Comment by qwerty123-noname** [comment]
GitHub Pages was add to my work! **Thx for help @Peter-developer01!**
